create table dq_rule_set (
    rule_set_id      number generated by default as identity primary key,
    rule_set_code    varchar2(50) not null,
    rule_set_name    varchar2(200) not null,
    description      varchar2(1000),
    enabled_flag     char(1) default 'Y' not null,
    constraint uq_dq_rule_set_code unique(rule_set_code),
    constraint ck_dq_rule_set_enabled check(enabled_flag in ('Y','N'))
);

create table dq_rule (
    rule_id           number generated by default as identity primary key,
    rule_code         varchar2(100) not null,
    rule_name         varchar2(200) not null,
    target_table      varchar2(128) not null,
    key_expression    varchar2(400) not null,
    failure_condition varchar2(2000) not null,
    severity          varchar2(20) default 'ERROR' not null,
    enabled_flag      char(1) default 'Y' not null,
    constraint uq_dq_rule_code unique(rule_code),
    constraint ck_dq_rule_severity check(severity in ('INFO','WARNING','ERROR','CRITICAL')),
    constraint ck_dq_rule_enabled check(enabled_flag in ('Y','N'))
);

create table dq_rule_set_member (
    rule_set_id number not null,
    rule_id     number not null,
    rule_order  number default 10 not null,
    primary key(rule_set_id, rule_id),
    constraint fk_dq_rsm_set foreign key(rule_set_id) references dq_rule_set(rule_set_id),
    constraint fk_dq_rsm_rule foreign key(rule_id) references dq_rule(rule_id)
);

create table dq_execution (
    execution_id      number generated by default as identity primary key,
    rule_set_id       number not null,
    rule_set_code     varchar2(50) not null,
    status            varchar2(20) not null,
    started_at        timestamp default systimestamp not null,
    finished_at       timestamp,
    rows_checked      number default 0 not null,
    rules_executed    number default 0 not null,
    violations_found  number default 0 not null,
    dq_score          number(7,2),
    error_message     varchar2(4000),
    constraint fk_dq_execution_set foreign key(rule_set_id) references dq_rule_set(rule_set_id),
    constraint ck_dq_execution_status check(status in ('RUNNING','COMPLETED','FAILED'))
);

create table dq_violation (
    violation_id      number generated by default as identity primary key,
    execution_id      number not null,
    rule_id           number not null,
    business_key      varchar2(1000),
    severity          varchar2(20) not null,
    violation_message varchar2(2000),
    detected_at       timestamp default systimestamp not null,
    constraint fk_dq_violation_exec foreign key(execution_id) references dq_execution(execution_id),
    constraint fk_dq_violation_rule foreign key(rule_id) references dq_rule(rule_id)
);
